### ISSUE TITLE
Create a class to generate the zacros initial state (state_input.dat)

### ISSUE THREAD

**Issue by nfaguirrec** [NLESC-JCER/pyZacros#33]

**Comment by lopeztarifa** [comment]
@nfaguirrec can you describe what you have on mind?
Thanks!

**Comment by nfaguirrec** [comment]
Below there is an example of the kind of files we need to generate. This file describes which binding sites are occupied at the beginning of the simulation. By default, it is not necessary because all sites are assumed empty. However, for the beta product out example only involves adsorbed species, and so we need it.

**state_input.dat**
```
initial_state
   seed_on_sites O1* 10
   seed_on_sites O1* 11
   seed_on_sites O1* 12
   seed_on_sites O1* 13
   seed_on_sites O1* 14
   seed_on_sites O1* 15
   seed_on_sites O1* 16
   seed_on_sites O1* 17
   seed_on_sites O1* 18
end_initial_state
```
