### ISSUE TITLE
Remove sett.KMCOutput.path, add KMCJob(name='Zacros')

### ISSUE THREAD

**Issue by lopeztarifa** [NLESC-JCER/pyZacros#45]
In order to get more aligned to [PLAMS job class](https://github.com/SCM-NV/PLAMS/blob/master/core/basejob.py), the sett.KMCOutput.path will be moved from KMCSettings and added to KMCJob as attribute:

```
job = KMCJob( lattice=loader.lattice, clusters=loader.clusters,
 mechanism=loader.mechanism, initialState=initialState,
settings=settings, name='ZACROS' )
```

**Comment by nfaguirrec** [comment]
I fixed this in the last commit
